In [1]:
# https://github.com/wkentaro/pytorch-for-numpy-users/blob/master/README.md

#https://stackoverflow.com/questions/51858067/parsing-csv-into-pytorch-tensors

#https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

#https://www.kaggle.com/kanncaa1/pytorch-tutorial-for-deep-learning-lovers

#https://medium.com/biaslyai/learn-pytorch-basics-6d433f186b7a


In [2]:
import numpy as np
import torch as pt
# import tensorflow as tf
# import tensorflow.keras as ktf

In [3]:
#1. numpy
np_a = np.arange(1,10)
print(np_a)

#torch


#2. How to create a 1D tensor in torch ?
pt_a = pt.arange(1,10)
print(pt_a)


#tensorflow
#sess = tf.Session()
#tf_a = tf.range(1,10)
#sess.run(tf_a)

#with tf.Session() as sess:
#    print(":::::::tf",tf_a.eval())




[1 2 3 4 5 6 7 8 9]
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
#3. How to create a boolean tensor in torch ?

# error :: Can’t convert np.ndarray of type numpy.bool_

bool_array = np.ones((3,4),dtype=np.uint8)
pt.from_numpy(bool_array)


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [5]:
#4. How to extract items that satisfy a given condition from 1D tensor in torch ?

arr = pt.tensor([1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1]


tensor([1, 3, 5, 7, 9])

In [6]:
#5. How to replace items that satisfy a condition with another value in tensor ?


arr = pt.tensor([1,2,3,4,5,6,7,8,9])

arr[arr % 2 == 1] = -1

arr

tensor([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
#6. How to replace items that satisfy a condition without affecting the original tensor in torch ?

arr = pt.tensor([1,2,3,4,5,6,7,8,9])

replace_arr = pt.tensor([-1])

output = pt.where(arr % 2 == 1, replace_arr, arr)
output

tensor([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
#7. How to reshape an tensor in torch ?

arr = pt.arange(0,9)
arr.reshape(3,-1)


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
#8. how to stack tensor vertically in torch ?

a = pt.arange(10).reshape(2, -1)
b = pt.tensor(1).repeat(10).reshape(2,-1)


print("concatenate:\n",pt.cat([a,b], 0))
print("vstack:\n",pt.stack([a,b], 0))


concatenate:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
vstack:
 tensor([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]])


In [10]:
#9. How to stack two arrays horizontally in torch ?

a = pt.arange(10).reshape(2, -1)
b = pt.tensor(1).repeat(10).reshape(2,-1)

print("concatenate:\n",pt.cat([a,b], 1))
print("hstack:\n",pt.stack([a,b], 1))


concatenate:
 tensor([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
hstack:
 tensor([[[0, 1, 2, 3, 4],
         [1, 1, 1, 1, 1]],

        [[5, 6, 7, 8, 9],
         [1, 1, 1, 1, 1]]])


In [11]:
#10. How to generate custom sequences in torch without hardcoding in torch ?

t = pt.tensor([1,2,3])

t1=t.repeat(3)
t2=t.repeat(3).reshape(3,-1).transpose(1,0).reshape(-1)

pt.cat([t1,t2],0)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
#11. How to remove from one array those items that exist in another in torch ?

t1 = pt.tensor([1,2,3,4,5])
t2 = pt.tensor([5,6,7,8,9])

indices = pt.ones_like(t1, dtype = pt.uint8)
for elem in t2:
    indices = indices & (t1 != elem)
    
print("indices:::",indices)
intersection = t1[indices]  
intersection

indices::: tensor([1, 1, 1, 1, 0], dtype=torch.uint8)


tensor([1, 2, 3, 4])

In [13]:
#12. How to get the common items between two tensor torch?

a = pt.tensor([1,2,3,2,3,4,3,4,5,6])
b = pt.tensor([7,2,3,2,7,4,9,4,9,8])

equal_data = pt.eq(a, b)
pt.unique(pt.cat([a[equal_data],b[equal_data]]))

tensor([2, 3, 4])

In [14]:
#13. How to get the positions where elements of two tensor match pytorch

a = pt.tensor([1,2,3,2,3,4,3,4,5,6])
b = pt.tensor([7,2,10,2,7,4,9,4,9,8])

pt.nonzero(pt.eq(a,b))

tensor([[1],
        [3],
        [5],
        [7]])

In [15]:
#14. How to extract all numbers between a given range from a pytorch tensor?

a = pt.tensor([11,12,13,14,15,16])
mask = (a >=11) & (a <= 15)
a[mask]


tensor([11, 12, 13, 14, 15])

In [16]:
#15. How to pick max value from two tensor in pytorch?

a = pt.tensor([5, 7, 9, 8, 6, 4, 5])
b = pt.tensor([6, 3, 4, 8, 9, 7, 1])

pt.max(a,b)


tensor([6, 7, 9, 8, 9, 7, 5])

In [17]:
#16. How to swap two columns in a 2d tensor in pytorch?

a = pt.tensor([[1,2,3],[3,4,5],[7,8,9]])

i1 = pt.index_select(a, 1, pt.LongTensor([0,2]))
i2 = pt.index_select(a, 1, pt.LongTensor([1]))

pt.cat((i1,i2), dim=1)



tensor([[1, 3, 2],
        [3, 5, 4],
        [7, 9, 8]])

In [18]:
#17. How to swap two rows in a 2d tensor in pytorch?

a = pt.tensor([[1,2,3],[3,4,5],[7,8,9]])

i1 = pt.index_select(a, 0, pt.LongTensor([0,2]))
i2 = pt.index_select(a, 0, pt.LongTensor([1]))
print(i2)
#pt.cat((i1,i2), dim=0)



tensor([[3, 4, 5]])


In [19]:
#18. How to reverse the rows of a 2d tensor in pytorch ?

aa = pt.tensor([[1,2,3],[4,5,6],[7,8,9]])
idx = [i for i in range(aa.size(0)-1, -1, -1)]
idx = pt.LongTensor(idx)
inverted_tensor = pt.index_select(aa,0,idx)
print("Before ::",aa)
print("After ::",inverted_tensor)

Before :: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
After :: tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])


In [20]:
#19. How to reverse the columns of a 2d tensor in pytorch ?

aa = pt.tensor([[1,2,3],[4,5,6],[7,8,9]])
idx = [i for i in range(aa.size(0)-1, -1, -1)]
idx = pt.LongTensor(idx)
inverted_tensor = pt.index_select(aa,1,idx)
print("Before ::",aa)
print("After ::",inverted_tensor)

Before :: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
After :: tensor([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]])


In [21]:
#20  How to create a 2D tensor containing random floats between 5 and 10?

pt.empty(2,3).uniform_(5,10).type(pt.FloatTensor)

tensor([[8.2637, 9.7855, 6.2776],
        [7.5562, 5.2533, 7.3286]])

In [22]:
#21 How to print only 3 decimal places in pyorch tensor?

arr = pt.rand((3,3))
pt.set_printoptions(precision=3)

arr

tensor([[0.752, 0.085, 0.889],
        [0.259, 0.107, 0.156],
        [0.990, 0.867, 0.998]])

In [23]:
# 22 How to limit the number of items printed in output of torch tensor

arr = pt.arange(2,50)
pt.set_printoptions(threshold=5)
arr

tensor([ 2,  3,  4,  ..., 47, 48, 49])

In [24]:
#23 How to print the full pytorch tensor without truncating
#https://discuss.pytorch.org/t/print-a-verbose-version-of-a-tensor/11201

arr = pt.arange(2,50)
pt.set_printoptions(profile="default")
arr

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
#24 Autograd
#https://medium.com/biaslyai/pytorch-introduction-to-neural-network-feedforward-neural-network-model-e7231cff47cb
#https://medium.com/@tomgrek/building-your-first-neural-net-from-scratch-with-pytorch-56b0e9c84d54

import torch 
x = torch.ones(1, requires_grad=True)
print(x.grad)    # returns None


x = torch.ones(1, requires_grad=True)
print("x::::",x)
y = x + 2
z = y * y * 2
z.backward()     # automatically calculates the gradient
print(x.grad)    # ∂z/∂x = 12

None
x:::: tensor([1.], requires_grad=True)
tensor([12.])


In [26]:
z = pt.zeros(3, 2)
x = z.view(2, 3)
z.fill_(1)
print("x:::::",x)
print("z:::::",z)

x::::: tensor([[1., 1., 1.],
        [1., 1., 1.]])
z::::: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [27]:
#unsqueeze pytorch
#numpy-newaxis-work

#https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it


x = pt.tensor([1, 2, 3, 4])

x1 = torch.unsqueeze(x, 0)
x2 = torch.unsqueeze(x, 1)
print("unsqueeze 0::",x1)
print("unsqueeze 1::",x2)

unsqueeze 0:: tensor([[1, 2, 3, 4]])
unsqueeze 1:: tensor([[1],
        [2],
        [3],
        [4]])


In [28]:
x3 = torch.squeeze(x1, 0)
x3

tensor([1, 2, 3, 4])

In [29]:
#https://stackoverflow.com/questions/51143206/difference-between-tensor-permute-and-tensor-view-in-pytorch

a = torch.tensor([[1,2],[3,4]])
print("a::::",a)

a1 = a.permute(1, 0)
print("a1::::",a1)

a2 = a.permute(0, 1)
print("a2::::",a2)


a:::: tensor([[1, 2],
        [3, 4]])
a1:::: tensor([[1, 3],
        [2, 4]])
a2:::: tensor([[1, 2],
        [3, 4]])


In [30]:
#unsqueeze pytorch
#numpy-newaxis-work

#https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it


# how to convert 1D tensor to 2D tensor

#x_train  = torch.linspace(-1, 1, 101)    # 1D tensor

x_train  = torch.tensor([0,1,2,3,4,6,7,8,9,10,11,12])    # 1D tensor

print("len of tensor:::",len(x_train))

print("1D tensor",x_train.size())

#x_train = x_train.view(12, 1) # convert to 2D tensor
x_train = x_train.unsqueeze(1) # convert to 2D tensor

print("2D tensor", x_train.size())

#x_train = x_train.view(11, 1) # convert to 3D tensor
x_train3D_unsqueeze = x_train.unsqueeze(-1) # convert to 3D tensor
print("3D tensor", x_train3D_unsqueeze.size())

x_train3D_reshape =  x_train.reshape(2,2,3)
print("3D reshape tensor", x_train3D_reshape.size())


len of tensor::: 12
1D tensor torch.Size([12])
2D tensor torch.Size([12, 1])
3D tensor torch.Size([12, 1, 1])
3D reshape tensor torch.Size([2, 2, 3])


In [31]:
#https://discuss.pytorch.org/t/torch-repeat-and-torch-expand-which-to-use/27969

a = torch.Tensor([[0,1,2],[3,4,5],[6,7,8]])
a.unsqueeze_(-1)
a = a.expand(3,3,11)
a.size()

torch.Size([3, 3, 11])

In [32]:
#create constructors with empty_like tensor

x = torch.zeros(2,3)
empty_like = torch.empty_like(x)
print("::::",empty_like)

:::: tensor([[2.7224e+20, 7.7782e+31, 4.7429e+30],
        [1.3818e+31, 1.7225e+22, 1.4602e-19]])


In [33]:
# create numerical ranges with linspace return 1-D tensor

x_linespace = torch.linspace(-10, 10, steps=5)
x_linespace

tensor([-10.,  -5.,   0.,   5.,  10.])

In [34]:
# Linear algebra pytorch.mm

aa = torch.tensor([[1, 1, 1],[2, 2, 2]])

bb = torch.tensor([[3, 3, 3],[4, 4, 4],[5, 5, 5]])

cc = torch.tensor([[3, 3, 3],[4, 4, 4]])


#not working with "cc" tensor bcoz of ,
#torch.mm(aa,cc) bcoz of mat1 is a (n×m) tensor, mat2 is a (m×p) tensor, out will be a (n×p) tensor.

#working Just calculation:::: 1*3+1*4+1*5
# 

torch.mm(aa,bb)



tensor([[12, 12, 12],
        [24, 24, 24]])

In [35]:
#get diagonal from tensor

bb = torch.tensor([[4, 3, 3],[4, 6, 4],[5, 5, 7]])
print("::::",torch.diag(bb,0))
print("::::",torch.diag(bb,1))
print(":::::",torch.diag(bb,2))

:::: tensor([4, 6, 7])
:::: tensor([3, 4])
::::: tensor([3])


In [36]:
#get lower triangular part of the tensor 

bb = torch.tensor([[4, 3, 3],[4, 6, 4],[5, 5, 7]])

print(torch.tril(bb,0))
print(torch.tril(bb,1))


tensor([[4, 0, 0],
        [4, 6, 0],
        [5, 5, 7]])
tensor([[4, 3, 0],
        [4, 6, 4],
        [5, 5, 7]])


In [37]:
#get upper triangular part of the tensor 

bb = torch.tensor([[4, 3, 3],[4, 6, 4],[5, 5, 7]])

print(torch.triu(bb,0))
print(torch.triu(bb,1))

tensor([[4, 3, 3],
        [0, 6, 4],
        [0, 0, 7]])
tensor([[0, 3, 3],
        [0, 0, 4],
        [0, 0, 0]])


In [38]:
# calculate stride of the tensor (memory)
#https://www.jessicayung.com/numpy-arrays-memory-and-strides/

bb = torch.tensor([[4, 3, 3],[4, 6, 4],[5, 5, 7]])

print("dtype::::",bb.dtype)
print("stride:::::",bb.stride())

dtype:::: torch.int64
stride::::: (3, 1)


In [39]:
#select indexing based on tensor indices 

src = torch.tensor([[4, 3, 5],[6, 7, 8]])

torch.take(src, torch.tensor([0, 1, 2, 5]))

tensor([4, 3, 5, 8])

In [40]:
# resize_  Resizes self tensor to the specified size. 
#If the number of elements is larger than the current storage size, then the underlying storage is resized to fit the new number of elements


x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(":::",x.resize_(2, 2))
print("::::",x.resize_(3, 3))

::: tensor([[1, 2],
        [3, 4]])
:::: tensor([[              1,               2,               3],
        [              4,               5,               6],
        [140114718097420,     64424509440,               0]])


In [41]:
#sort tensor 

x = torch.tensor([[2,1], [4,3], [7,5]])
print(":::",x.sort())
print("::::dim",x.dim())
print(":::",torch.sort(x))


::: torch.return_types.sort(
values=tensor([[1, 2],
        [3, 4],
        [5, 7]]),
indices=tensor([[1, 0],
        [1, 0],
        [1, 0]]))
::::dim 2
::: torch.return_types.sort(
values=tensor([[1, 2],
        [3, 4],
        [5, 7]]),
indices=tensor([[1, 0],
        [1, 0],
        [1, 0]]))


In [42]:
#flip tensor

x = torch.tensor([[2,1], [4,3], [7,5],[8,9]])
print("::::",x.flip(0))
print("::::",x.flip(1))
print("::::",x.flip([0,1]))
#print("::::",x.flip([1,0])) output are same

:::: tensor([[8, 9],
        [7, 5],
        [4, 3],
        [2, 1]])
:::: tensor([[1, 2],
        [3, 4],
        [5, 7],
        [9, 8]])
:::: tensor([[9, 8],
        [5, 7],
        [3, 4],
        [1, 2]])


In [43]:
# trace tensor Returns the sum of the elements of the diagonal of the input matrix.

a = torch.arange(1.,10.).view(3,3)

print("::::",torch.trace(a))


:::: tensor(15.)


In [44]:
# cumsum in tensor 

a = torch.arange(1,10)

torch.cumsum(a,dim=0)

tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [45]:
#Returns the indices of all elements in the input tensor.

a = torch.tensor([[1,2,3],[4,5,6],[-1,0,1]])
torch.argmax(a)


tensor(5)

In [46]:
# Performs a matrix-vector product of the matrix.

mat = torch.tensor([[2,2,3],[4,5,6]])
print(mat.size())
vec = torch.tensor([1,2,3])

"""
2*1 + 2*2 + 3*3  
1*4 + 2*5 + 3*6

"""

ans = torch.mv(mat, vec)

print(ans)

torch.Size([2, 3])
tensor([15, 32])


In [47]:
#get items from tensor

a = torch.Tensor([[1, 2], [3, 4]])

# replace an element at position 0, 0
a[0][0] = 5

# access an element at position 1, 0
print(a[1][0])
print(a[1][0].item())

tensor(3.)
3.0


In [48]:
#tensor requires_grad
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()

out.backward()
x.grad
x.grad


tensor([[ 2., -2.],
        [ 2.,  2.]])

In [49]:
#A tensor can be split between multiple chunks

x = torch.tensor([[2, 2], [1, 1],[3, 4],[8, 9]])

torch.chunk(x,2)

(tensor([[2, 2],
         [1, 1]]), tensor([[3, 4],
         [8, 9]]))

In [50]:
#unbind function removes a dimension from a tensor

x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

print( "::::::x", x)

torch.unbind(x,1)

::::::x tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


(tensor([ 1,  4,  7, 10, 13]),
 tensor([ 2,  5,  8, 11, 14]),
 tensor([ 3,  6,  9, 12, 15]))

In [51]:
#Bernoulli distribution 

x = torch.Tensor(4,4).uniform_(0,1)
torch.bernoulli(x)

tensor([[0., 0., 1., 0.],
        [0., 0., 1., 1.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])

In [52]:
#To compute standard  deviation  and mean

print(torch.normal(mean=torch.arange(1.,11.)))
#print(torch.normal(std=torch.arange(1,0,-0.1)))

print(torch.normal(mean=torch.arange(1.,11.), std=torch.arange(1,0,-0.1)))

tensor([ 1.0382,  2.8145,  2.6497,  4.4358,  4.1428,  6.1307,  7.1371,  7.6426,
         8.4751, 11.1289])
tensor([ 0.6191,  1.0408,  2.4983,  4.8560,  4.1512,  6.5729,  6.9811,  8.1268,
         8.8706, 10.1291])


In [53]:
# To compute the gradient of the two data lists requires computations of a loss function

import torch
from torch.autograd import Variable

x_data = [11.0, 22.0, 33.0]
y_data = [21.0, 14.0, 64.0]

w = Variable(torch.tensor([1.0]),requires_grad=True) # any random variable

#print("predict (before training)", 4, forward(4).data[0])



def forward(x):
    return x * w

def loss(x, y):
    y_pred = forward(x)
    #error get like (MSE)
    return (y_pred - y) * (y_pred - y)



for epoch in range(10):
    for x_val , y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("grad", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data
        w.grad.data.zero_()

    print(":::::",epoch, l.data[0])

grad 11.0 21.0 tensor(-220.)
grad 22.0 14.0 tensor(2481.6001)
grad 33.0 64.0 tensor(-51303.6484)
::::: 0 tensor(604238.8125)
grad 11.0 21.0 tensor(118461.7578)
grad 22.0 14.0 tensor(-671630.6875)
grad 33.0 64.0 tensor(13114108.)
::::: 1 tensor(3.9481e+10)
grad 11.0 21.0 tensor(-30279010.)
grad 22.0 14.0 tensor(1.7199e+08)
grad 33.0 64.0 tensor(-3.3589e+09)
::::: 2 tensor(2.5900e+15)
grad 11.0 21.0 tensor(7.7553e+09)
grad 22.0 14.0 tensor(-4.4050e+10)
grad 33.0 64.0 tensor(8.6030e+11)
::::: 3 tensor(1.6991e+20)
grad 11.0 21.0 tensor(-1.9863e+12)
grad 22.0 14.0 tensor(1.1282e+13)
grad 33.0 64.0 tensor(-2.2034e+14)
::::: 4 tensor(1.1146e+25)
grad 11.0 21.0 tensor(5.0875e+14)
grad 22.0 14.0 tensor(-2.8897e+15)
grad 33.0 64.0 tensor(5.6436e+16)
::::: 5 tensor(7.3118e+29)
grad 11.0 21.0 tensor(-1.3030e+17)
grad 22.0 14.0 tensor(7.4013e+17)
grad 33.0 64.0 tensor(-1.4455e+19)
::::: 6 tensor(4.7966e+34)
grad 11.0 21.0 tensor(3.3374e+19)
grad 22.0 14.0 tensor(-1.8957e+20)
grad 33.0 64.0 tensor(3

In [54]:
#define matrix 

mat1 = torch.FloatTensor(4,4).uniform_(0,1)
mat2 = torch.FloatTensor(5,4).uniform_(0,1)

#define vector
vac1 = torch.FloatTensor(4).uniform_(0,1)


#scalar addition

mat1 + 10.5

#scalar subtraction

mat2 - 0.50


# vecotor and matrix addition

c= mat1 + vac1
c

tensor([[0.8323, 0.1120, 0.8695, 0.7284],
        [0.7497, 0.9765, 0.8989, 1.0014],
        [0.8027, 0.2768, 0.9374, 0.6354],
        [0.8371, 0.2463, 0.5359, 1.2751]])

In [55]:
import torch

torch.__version__

t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0])

t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4])



def model(t_u, w, b):
    return w * t_u + b

def loss_fn(t_p, t_c):
    squard_diff = (t_p - t_c)**2
    return squard_diff.mean()


w = torch.ones(1)
b = torch.zeros(1)

t_p = model(t_u, w, b)
print(t_p)


loss= loss_fn(t_p, t_c)

print(loss)


delta = 0.1

loss_rate_of_change_w = (loss_fn(model(t_u, w + delta,b), t_c)  - loss_fn(model(t_u,w - delta, b), t_c)) / (2.0 * delta)


learning_rate = 1e-2

w = w - learning_rate * loss_rate_of_change_w

loss_rate_of_change_b = (loss_fn(model(t_u, w, b + delta), t_c)  - 
                         loss_fn(model(t_u, w, b - delta), t_c)) / (2.0 * delta)


b = b - learning_rate * loss_rate_of_change_b
b

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000])
tensor(1656.5790)


tensor([40.])

In [56]:
#MSELoss functions

import torch

from torch import nn
loss = nn.MSELoss()

input = torch.randn(10,5, requires_grad=True)
target = torch.randn(10, 5)

output = loss(input, target)

output.backward()
output

tensor(1.6799, grad_fn=<MseLossBackward>)

In [57]:
#use of torch.no_grad in pytorch 

x = torch.randn(3, requires_grad=True)

print(x.requires_grad)

print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)


True
True
False


In [58]:
# Use stride and size to track the memory layout:

a = torch.randn(3, 4, 5)
b = a.permute(1, 2, 0)
c = b.contiguous()
d = a.contiguous()
# a has "standard layout" (also known as C layout in numpy) descending strides, and no memory gaps (stride(i-1) == size(i)*stride(i))
print (a.shape, a.stride(), a.data_ptr())
# b has same storage as a (data_ptr), but has the strides and sizes swapped around
print (b.shape, b.stride(), b.data_ptr())
# c is in new storage, where it has been arranged in standard layout (which is "contiguous")
print (c.shape, c.stride(), c.data_ptr())
# d is exactly as a, as a was contiguous all along
print (d.shape, d.stride(), d.data_ptr())


torch.Size([3, 4, 5]) (20, 5, 1) 62404224
torch.Size([4, 5, 3]) (5, 1, 20) 62404224
torch.Size([4, 5, 3]) (15, 3, 1) 62386624
torch.Size([3, 4, 5]) (20, 5, 1) 62404224
